//
//  SignUpRouter.swift
//  SignUp
//
//  Created Z on 1/16/20.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpRouter: SignUpWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(title: String) -> UIViewController {
        
        let view = SignUpViewController(nibName: nil, bundle: nil)
        let interactor = SignUpInteractor()
        let router = SignUpRouter()
        let presenter = SignUpPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.navigationItem.title = title
        
        return view
    }
    
    // MARK: - make login
    func login() {
        openLink()
    }
    
    // MARK: - make link
    func openLink() {
        let view = SignInRouter.createModule(title: "Sign in")
        self.viewController?.navigationController?.pushViewController(view, animated: true)
        print("link sign up")
    }
}
