//
//  SignUpInteractor.swift
//  SignUp
//
//  Created Z on 1/16/20.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpInteractor: SignUpInteractorProtocol {

    weak var presenter: SignUpPresenterProtocol?
    
    let signUpModel = LoginModel()
    
    var statusHidePassword: Bool = true
    var statusHideConfirm: Bool = true
    
    func isHidePassword()-> Bool {
        return statusHidePassword
    }
    
    func isHideConfirm()-> Bool {
        return statusHideConfirm
    }
    
    func changeStatusHidePassword() {
        statusHidePassword = !statusHidePassword
    }
    
    func changeStatusHideConfirm() {
        statusHideConfirm = !statusHideConfirm
    }
    
    func setLogin(login: String) {
        signUpModel.login = login
        signUpModel.checkLogin = checkLogin(login: signUpModel.login)
    }
    
    func getLogin()->String {
        return signUpModel.login
    }
    
    func getStatusCheckLogin()->Check {
        return signUpModel.checkLogin
    }
    
    func setPassword(password: String) {
        var passwordNew = password
        if (isHidePassword()) {
            let password = getPassword()
            passwordNew = changeHidePassword(password: password, passwordHide: passwordNew)
        }
        signUpModel.password = passwordNew
        signUpModel.checkPassword = checkPassword(password: signUpModel.password)
    }
    
    func setConfirm(confirm: String) {
        var passwordNew = confirm
        if (isHideConfirm()) {
            let password = getConfirm()
            passwordNew = changeHidePassword(password: password, passwordHide: passwordNew)
        }
        signUpModel.confirm = passwordNew
        signUpModel.checkConfirm = checkConfirm(confirm: signUpModel.confirm)
    }
    
    func getPassword()->String {
        return signUpModel.password
    }
    
    func getConfirm()->String {
        return signUpModel.confirm
    }
    
    func getPasswordForShow()->String {
        let password = getPassword()
        if (isHidePassword()) {
            return String(repeating: CharactersChecking.charHidePassword, count: password.count)
        }
        else {
            return password
        }
    }
    
    func getConfirmForShow()->String {
        let password = getConfirm()
        if (isHideConfirm()) {
            return String(repeating: CharactersChecking.charHidePassword, count: password.count)
        }
        else {
            return password
        }
    }
    
    func getStatusCheckPassword()->Check {
        return signUpModel.checkPassword
    }
    
    func getStatusCheckConfirm()->Check {
        return signUpModel.checkConfirm
    }
    
    // MARK: previous common check login and password
    func checkAll(str: String, maxCount: Int)->Check {
        let count = str.count
        guard (count >= 5 && count <= maxCount) else {
            return Check.no("Characters number must >4 and <\(maxCount)")
        }
        for char in CharactersChecking.restrict_characters {
            if str.contains(char) {
                return Check.no("Restricted characters - \"\(char)\"")
            }
        }
        return Check.yes
    }
    
    func checkLogin(login: String)->Check {
        let check: Check
        check = checkAll(str: login, maxCount: 25)
        guard check == .yes else {
            return check
        }
        guard login.contains("@") else {
            return Check.no("Login must contains - \"@\"")
        }
        var loginChar = Array(login)
        var index = loginChar.lastIndex(of: ".")
        guard index != nil else {
            return Check.no("Login must contains - \".\"")
        }
        while (index != nil) {
            guard (index! < loginChar.count - 2) else {
                return Check.no("Login must contains 2 characters after \".\"")
            }
            loginChar.removeLast(loginChar.count-index!)
            index = loginChar.lastIndex(of: ".")
        }
        if !(chackSign(login: login)) {
            return Check.no("Login already exist. Choose another.")
        }
        return Check.yes
    }
    
    func checkPassword(password: String)->Check {
        let check: Check
        check = checkAll(str: password, maxCount: 20)
        guard check == .yes else {
            return check
        }
        
        for check in CharactersChecking.checkingStrings {
            var checkFlag = false
            for char in check {
                if password.contains(char) {
                    checkFlag = true
                    break
                }
            }
            guard (checkFlag) else {
                return Check.no("Password must contains - number, latin characters lowercase and uppercase, special character")
            }
        }
        return Check.yes
    }
    
    func checkConfirm(confirm: String)->Check {
        guard signUpModel.password == signUpModel.confirm else {
            return Check.no("Passwords not identical")
        }
     
        return Check.yes
    }
    
    func changeHidePassword(password: String, passwordHide: String)->String {
        var password = password
        guard (passwordHide.count > 0) else { return ""}
        guard (passwordHide.count >= password.count) else { return "" }
        guard (passwordHide.count > password.count) else { return password }
        guard let _ = passwordHide.lastIndex(where: {$0 != CharactersChecking.charHidePassword}) else { return "" }
        var newPassword = ""
        for char in passwordHide {
            if (char == CharactersChecking.charHidePassword) {
                newPassword.append(password.removeFirst())
            }
            else {
                newPassword.append(char)
            }
        }
        return newPassword
    }
    
    func saveSignUp() {
        var signDictionry = ReadServise.getUserDef()
        signDictionry[signUpModel.login] = signUpModel.password
        SaveServise.saveUserDef(signDictionry)
    }
    
    func chackSign(login: String) -> Bool {
        let signDictionry = ReadServise.getUserDef()
        
        if let _ = signDictionry[login] {
            return  false
        }
        return  true
    }
}
