//
//  SignUpPresenter.swift
//  SignUp
//
//  Created Z on 1/16/20.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPresenter: SignUpPresenterProtocol {

    weak private var view: SignUpViewProtocol?
    var interactor: SignUpInteractorProtocol?
    private let router: SignUpWireframeProtocol
    
    init(interface: SignUpViewProtocol, interactor: SignUpInteractorProtocol?, router: SignUpWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func setLogin(login: String) {
        interactor?.setLogin(login: login)
        updateView()
    }
    
    func setPassword(password: String) {
        interactor?.setPassword(password: password)
        updateView()
    }
    
    func setConfirm(confirm: String) {
        interactor?.setConfirm(confirm: confirm)
        updateView()
    }
    
    func getPasswordForShow()->String {
        guard let password = interactor?.getPasswordForShow() else { return "" }
        return password
    }
    
    func getConfirmForShow()->String {
        guard let password = interactor?.getConfirmForShow() else { return "" }
        return password
    }
    
    func changeStatusHidePassword()->String {
        guard let interactor = interactor else { return "" }
        interactor.changeStatusHidePassword()
        if (interactor.isHidePassword()) {
            view?.setTittlePasswordButtonShow()
        }
        else {
            view?.setTittlePasswordButtonHide()
        }
        return getPasswordForShow()
    }
    
    func changeStatusHideConfirm()->String {
        guard let interactor = interactor else { return "" }
        interactor.changeStatusHideConfirm()
        if (interactor.isHideConfirm()) {
            view?.setTittleConfirmButtonShow()
        }
        else {
            view?.setTittleConfirmButtonHide()
        }
        return getConfirmForShow()
    }
    
    func updateView() {
        guard let interactor = interactor else { return }
        let checkLogin: Check = interactor.getStatusCheckLogin()
        if case .no(let error) = checkLogin {
            view?.switchLoginButton(isHide: true, errorText: error)
            view?.switchPasswordTextFild(isHide: true, errorText: error)
            view?.switchConfirmTextFild(isHide: true, errorText: error)
            
            return
        }
        view?.switchPasswordTextFild(isHide: false, errorText: "")
        view?.switchConfirmTextFild(isHide: false, errorText: "")
        
        let checkPassword: Check = interactor.getStatusCheckPassword()
        if case .no(let error) = checkPassword {
            view?.switchLoginButton(isHide: true, errorText: error)
            return
        }
        let checkConfirm: Check = interactor.getStatusCheckConfirm()
        if case .no(let error) = checkConfirm {
            view?.switchLoginButton(isHide: true, errorText: error)
            return
        }
        
        view?.switchLoginButton(isHide: false, errorText: "")
    }
    
    func clickLogin() {
        interactor?.saveSignUp()
        router.login()
    }
    
    func openLink() {
        router.openLink()
    }
}
