//
//  SignUpProtocols.swift
//  SignUp
//
//  Created Z on 1/16/20.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignUpWireframeProtocol: class {
    func login()
    func openLink()
}

//MARK: Presenter -
protocol SignUpPresenterProtocol: class {
    func setPassword(password: String)
    func setConfirm(confirm: String)
    func setLogin(login: String)
    func changeStatusHidePassword()->String
    func changeStatusHideConfirm()->String
    func getPasswordForShow()->String
    func getConfirmForShow()->String
    func clickLogin()
    func openLink()
}

//MARK: Interactor -
protocol SignUpInteractorProtocol: class {

    var presenter: SignUpPresenterProtocol?  { get set }
    
    func setLogin(login: String)
    func setPassword(password: String)
    func setConfirm(confirm: String)
    func getPassword()->String
    func getConfirm()->String
    func getLogin()->String
    func getStatusCheckLogin()->Check
    func getStatusCheckPassword()->Check
    func getStatusCheckConfirm()->Check
    func changeStatusHidePassword()
    func changeStatusHideConfirm()
    func isHidePassword()-> Bool
    func isHideConfirm()-> Bool
    func getPasswordForShow()->String
    func getConfirmForShow()->String
    func saveSignUp()
}

//MARK: View -
protocol SignUpViewProtocol: class {
    
    var presenter: SignUpPresenterProtocol?  { get set }
    
    func switchLoginButton(isHide: Bool, errorText: String)
    func switchPasswordTextFild(isHide: Bool, errorText: String)
    func switchConfirmTextFild(isHide: Bool, errorText: String)
    func setTittlePasswordButtonShow()
    func setTittlePasswordButtonHide()
    func setTittleConfirmButtonShow()
    func setTittleConfirmButtonHide()
}
