//
//  SignUpInteractor.swift
//  LoginScreen
//
//  Created Oleksander on 14.03.2020.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpInteractor: SignUpInteractorProtocol {

    weak var presenter: SignUpPresenterProtocol?
}
