//
//  LoginScreenProtocols.swift
//  LoginScreen
//
//  Created Z on 1/16/20.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginScreenWireframeProtocol: class {
    func login(login: String, password: String)
    func openLink()
}
//MARK: Presenter -
protocol LoginScreenPresenterProtocol: class {
    func setPassword(password: String)
    func setLogin(login: String)
    func changeStatusHidePassword()->String
    func getPasswordForShow()->String
    func clickLogin()
    func openLink()
}

//MARK: Interactor -
protocol LoginScreenInteractorProtocol: class {

    var presenter: LoginScreenPresenterProtocol?  { get set }
    
    func setLogin(login: String)
    func setPassword(password: String)
    func getPassword()->String
    func getLogin()->String
    func getStatusCheckLogin()->Check
    func getStatusCheckPassword()->Check
    func changeStatusHidePassword()
    func isHidePassword()-> Bool
    func getPasswordForShow()->String
}

//MARK: View -
protocol LoginScreenViewProtocol: class {
    
    var presenter: LoginScreenPresenterProtocol?  { get set }
    
    func switchLoginButton(isHide: Bool, errorText: String)
    func switchPasswordTextFild(isHide: Bool, errorText: String)
    func setTittlePasswordButtonShow()
    func setTittlePasswordButtonHide()
}
