//
//  SignInPresenter.swift
//  LoginScreen
//
//  Created Oleksander on 14.03.2020.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInPresenter: SignInPresenterProtocol {

    weak private var view: SignInViewProtocol?
    var interactor: SignInInteractorProtocol?
    private let router: SignInWireframeProtocol

    init(interface: SignInViewProtocol, interactor: SignInInteractorProtocol?, router: SignInWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func setLogin(login: String) {
        interactor?.setLogin(login: login)
        updateView()
    }
    
    func setPassword(password: String) {
        interactor?.setPassword(password: password)
        updateView()
    }
    
    func getPasswordForShow()->String {
        guard let password = interactor?.getPasswordForShow() else { return "" }
        return password
    }
    
    func changeStatusHidePassword()->String {
        guard let interactor = interactor else { return "" }
        interactor.changeStatusHidePassword()
        if (interactor.isHidePassword()) {
            view?.setTittlePasswordButtonShow()
        }
        else {
            view?.setTittlePasswordButtonHide()
        }
        return getPasswordForShow()
    }
    
    func updateView() {
        guard let interactor = interactor else { return }
        let checkLogin: Check = interactor.getStatusCheckLogin()
        if case .no(let error) = checkLogin {
            view?.switchLoginButton(isHide: true, errorText: error)
            view?.switchPasswordTextFild(isHide: true, errorText: error)
            return
        }
        view?.switchPasswordTextFild(isHide: false, errorText: "")
        
        let checkPassword: Check = interactor.getStatusCheckPassword()
        if case .no(let error) = checkPassword {
            view?.switchLoginButton(isHide: true, errorText: error)
            return
        }
        
        view?.switchLoginButton(isHide: false, errorText: "")
    }
    
    func clickLogin() {
        if (interactor?.chackSignin() ?? false) {
            router.login()
        }
        else {
            view?.switchLoginButton(isHide: true, errorText: "Login or password invalid.")
        }
    }
    
    func openLink() {
        router.openLink()
    }
    
    func clearUser() {
        setLogin(login: "")
        setPassword(password: "")
        updateView()
    }
}
