//
//  SignInRouter.swift
//  LoginScreen
//
//  Created Oleksander on 14.03.2020.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInRouter: SignInWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(title: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SignInViewController(nibName: nil, bundle: nil)
        let interactor = SignInInteractor()
        let router = SignInRouter()
        let presenter = SignInPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.navigationItem.title = title
        
        return view
    }
    
    // MARK: - make login
    func login() {
        print("-----Reasdy------")
    }
    
    // MARK: - make link
    func openLink() {
        self.viewController?.navigationController?.popToRootViewController(animated: true)
    }
}
