//
//  SignInProtocols.swift
//  SignIn
//
//  Created Oleksander on 14.03.2020.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignInWireframeProtocol: class {
    func login()
    func openLink()
}
//MARK: Presenter -
protocol SignInPresenterProtocol: class {
    func setPassword(password: String)
    func setLogin(login: String)
    func changeStatusHidePassword()->String
    func getPasswordForShow()->String
    func clickLogin()
    func openLink()
    func clearUser()
}

//MARK: Interactor -
protocol SignInInteractorProtocol: class {

    var presenter: SignInPresenterProtocol?  { get set }
    
    func setLogin(login: String)
    func setPassword(password: String)
    func getPassword()->String
    func getLogin()->String
    func getStatusCheckLogin()->Check
    func getStatusCheckPassword()->Check
    func changeStatusHidePassword()
    func isHidePassword()-> Bool
    func getPasswordForShow()->String
    func chackSignin() -> Bool
}

//MARK: View -
protocol SignInViewProtocol: class {
    
    var presenter: SignInPresenterProtocol?  { get set }
    
    func switchLoginButton(isHide: Bool, errorText: String)
    func switchPasswordTextFild(isHide: Bool, errorText: String)
    func setTittlePasswordButtonShow()
    func setTittlePasswordButtonHide()
}
