//
//  NamesInteractor.swift
//  LoginScreen
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NamesInteractor: NamesInteractorProtocol {

    weak var presenter: NamesPresenterProtocol?
    
    func requestName() {
        var resultName = [NamesModel]()
       
        ApiServise.shared.loadAPIRequest(url: "http://names.drycodes.com/10") { [weak self] (result: [String]?, error) in
            guard let self = self else { return }
            guard let result = result else { print(error as Any); return }
            guard let presenter = self.presenter else { return }
            for item in  result {
                let namesModel = NamesModel(name: item)
                resultName.append(namesModel)
            }
            presenter.updateName(resultName: resultName)
        }
    }
}
