//
//  NamesPresenter.swift
//  LoginScreen
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NamesPresenter: NamesPresenterProtocol {

    weak private var view: NamesViewProtocol?
    var interactor: NamesInteractorProtocol?
    private let router: NamesWireframeProtocol
    
    
    init(interface: NamesViewProtocol, interactor: NamesInteractorProtocol?, router: NamesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func requestName() {
        self.interactor?.requestName()
    }
    
    func countCell(section: Int)->Int {
        return interactor?.namesCount(section: section) ?? 0
    }

    func getName(section: Int, index: Int)->String {
        return interactor?.getName(section: section, index: index) ?? ""
    }
    
    func deleteName(section: Int, index: Int) {
        self.interactor?.deleteName(section: section, index: index)
        updateName()
    }
    
    func addName(name: String) {
        self.interactor?.addName(name: name)
        updateName()
    }
    
    func signOut() {
        self.router.closeView()
    }
    
    func closeView() {
        router.closeView()
    }
    
    func updateName() {
        self.view?.update()
    }
}
