//
//  NamesPresenter.swift
//  LoginScreen
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NamesPresenter: NamesPresenterProtocol {

    weak private var view: NamesViewProtocol?
    var interactor: NamesInteractorProtocol?
    private let router: NamesWireframeProtocol
    var resultName: [NamesModel]?
    
    init(interface: NamesViewProtocol, interactor: NamesInteractorProtocol?, router: NamesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func requestName() {
        self.interactor?.requestName()
    }
    
    func countCell()->Int {
        return resultName?.count ?? 0
    }

    func closeView() {
        router.closeView()
    }
    
    func updateName(resultName: [NamesModel]?) {
        self.resultName = resultName
        self.view?.update()
    }

    func getName(index: Int)->String {
        let name = resultName?[index].name ?? ""
        return name
    }
    
    func getNameModel(index: Int)->NamesModel? {
        return resultName?[index]
    }
    
    func signOut() {
        self.router.closeView()
    }
}
