//
//  NamesRouter.swift
//  LoginScreen
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NamesRouter: NamesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        let view = NamesViewController(nibName: nil, bundle: nil)
        let interactor = NamesInteractor()
        let router = NamesRouter()
        let presenter = NamesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func closeView() {
       self.viewController?.navigationController?.popToRootViewController(animated: true)
    }
}
