//
//  NamesViewController.swift
//  LoginScreen
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NamesViewController: UIViewController, NamesViewProtocol {

	var presenter: NamesPresenterProtocol?
    let cellIdentifier = "NamesCells"
    
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var namesTable: UITableView!
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Sign out", style: .plain, target: self, action: #selector(clickSignOutButtonBar))
        
        namesTable.delegate = self
        namesTable.dataSource = self
       
        namesTable.register(UINib(nibName: cellIdentifier, bundle: nil), forCellReuseIdentifier: cellIdentifier)
        namesTable.rowHeight = UITableView.automaticDimension
        namesTable.tableFooterView = UIView(frame: .zero)
        
        self.presenter?.requestName()
    }
    
    @objc func clickSignOutButtonBar() {
        presenter?.signOut()
    }
    
    func update() {
        DispatchQueue.main.async {
            self.namesTable.reloadData()
            self.activityIndicator.stopAnimating()
        }
    }
}

extension NamesViewController:  UITableViewDataSource, UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        let count = presenter?.countCell() ?? 0
        return count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath)
        if let cell = cell as? NamesCells {
            cell.name.text = self.presenter?.getName(index: indexPath.row)
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        guard let name = presenter?.getNameModel(index: indexPath.row) else { return }
        print(name)
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}
